package com.survey.microservice.base.model;

public enum ErrorMessageCode {
	
	OPERATION_DONE_SUCCESSFULLY("00","OPERATION_DONE_SUCCESSFULLY"),
	GENERAL_BACKEND_ERROR("-1","GENERAL_BACKEND_ERROR"), 
	NO_INPUT_PROVIDED("10001","NO_INPUT_PROVIDED"),
	NO_TITLE_PROVIDED("10002","NO_TITLE_PROVIDED"), 
	NO_SUCH_SURVEY_DEFINITION("10003","NO_SUCH_SURVEY_DEFINITION"), 
	PROVIDED_SURVEY_DEFINITION_IS_NOT_IN_DRAFT_STATUS("10004","PROVIDED_SURVEY_DEFINITION_IS_NOT_IN_DRAFT_STATUS"), 
	NO_SUCH_SURVEY_DEFINITION_QUESTION("10005","NO_SUCH_SURVEY_DEFINITION_QUESTION"), 
	PROVIDED_SURVEY_QUESTION_DEFINITION_IS_NOT_ASSOCIATED_WITH_PROVIDED_SURVEY_DEFINITION("10006","PROVIDED_SURVEY_QUESTION_DEFINITION_IS_NOT_ASSOCIATED_WITH_PROVIDED_SURVEY_DEFINITION"),
	NO_SUCH_SURVEY_DEFINITION_QUESTION_CHOICE("10007","NO_SUCH_SURVEY_DEFINITION_QUESTION_CHOICE"),
	PROVIDED_SURVEY_DEFINITION_QUESTION_CHOICE_IS_NOT_ASSOCIATED_WITH_PROVIDED_SURVEY_QUESTION_DEFINITION("10006","PROVIDED_SURVEY_DEFINITION_QUESTION_CHOICE_IS_NOT_ASSOCIATED_WITH_PROVIDED_SURVEY_QUESTION_DEFINITION"), 
	SURVEY_DEFINITION_SHOULD_CONTAINS_AT_LEAST_ONE_QUESTION("10007","SURVEY_DEFINITION_SHOULD_CONTAINS_AT_LEAST_ONE_QUESTION"),
	SURVEY_DEFINITION_QUESTION_SHOULD_CONTAINS_AT_LEAST_TWO_CHOICES("10007","SURVEY_DEFINITION_QUESTION_SHOULD_CONTAINS_AT_LEAST_TWO_CHOICES"), 
	NO_SUCH_SURVEY("10008","NO_SUCH_SURVEY"), 
	NO_SUCH_SURVEY_VERSION_FOR_PROVIDED_SURVEY("10009","NO_SUCH_SURVEY_VERSION_FOR_PROVIDED_SURVEY")

	
	
	;
	
	private String code;
	private String messageKey;
	
	

	public String getMessageKey() {
		return messageKey;
	}

	public void setMessageKey(String messageKey) {
		this.messageKey = messageKey;
	}

	ErrorMessageCode()
	{
		
	}
	
	ErrorMessageCode(String code)
	{
		this.code= code;
	}
	
	ErrorMessageCode(String code,String messageKey)
	{
		this.code= code;
		this.messageKey = messageKey;
	}
	
	public String getCode() {
		return code;
	}
	
}
