CREATE SEQUENCE SURVEY_QUESTION_CHOICE_PK_SEQ START WITH 1;  

CREATE TABLE SURVEY_QUESTION_CHOICE
(
       ID              						INT8 NOT NULL,
       SURVEY_QUESTION_ID        			INT8 NOT NULL,
       TITLE 	       						VARCHAR(50),
       CREATED_BY      						INT8,
       CREATED_DATE    						TIMESTAMP WITH TIME ZONE,
       PRIMARY KEY (ID)
);


ALTER TABLE SURVEY_QUESTION_CHOICE 
ADD 
CONSTRAINT SURVEY_QUESTION_CHOICE_SURVEY_QUESTION_ID_FK
FOREIGN KEY (SURVEY_QUESTION_ID) REFERENCES SURVEY_QUESTION;


CREATE INDEX SURVEY_QUESTION_CHOICE_SQ_INDEX ON SURVEY_QUESTION_CHOICE(SURVEY_QUESTION_ID);
