CREATE SEQUENCE SURVEY_DEFINITION_QUESTION_PK_SEQ START WITH 1;  

CREATE SEQUENCE SURVEY_QUESTION_CODE_SEQ START WITH 1000000;  


CREATE TABLE SURVEY_DEFINITION_QUESTION
(
       ID              				INT8 NOT NULL,
       SURVEY_DEFINITION_ID         INT8 NOT NULL,
       TITLE 	       				VARCHAR(50),
       CODE 	       				VARCHAR(20) NOT NULL,
       CREATED_BY					INT8,
       CREATED_DATE    				TIMESTAMP WITH TIME ZONE,
       primary key (ID)
);


ALTER TABLE SURVEY_DEFINITION_QUESTION 
ADD 
CONSTRAINT SURVEY_DEF_QUES_SURVEY_DEFINITION_ID_FK 
FOREIGN KEY (SURVEY_DEFINITION_ID) REFERENCES SURVEY_DEFINITION;

CREATE INDEX SURVEY_DEFINITION_QUESTION_SUR_DEF_INDX ON SURVEY_DEFINITION_QUESTION(SURVEY_DEFINITION_ID);