CREATE SEQUENCE SURVEY_PK_SEQ START WITH 1;  

CREATE SEQUENCE SURVEY_CODE_SEQ START WITH 1000000;  

CREATE TABLE SURVEY
(
       ID              		   INT8 NOT NULL,
       CODE 	       		   VARCHAR(12),
       TITLE 	       		   VARCHAR(40),
       SURVEY_STATUS 	       VARCHAR(40),
       SURVEY_VERSION          INT8 NULL,
       CREATED_BY      		   INT8,
       CREATED_DATE    		   TIMESTAMP WITH TIME ZONE,
       PRIMARY KEY (ID)
);



CREATE INDEX SURVEY_CODE_INDEX ON SURVEY(CODE);


ALTER TABLE SURVEY_DEFINITION 
ADD 
CONSTRAINT SURVEY_DEF__SURVEY_ID_FK 
FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY;

CREATE INDEX SURVEY_DEFINITION_SURVEY_ID_INDX ON SURVEY_DEFINITION(SURVEY_ID);